#!/usr/bin/env zsh

# if homebrew is installed (likely on macos) load its shellenv to be able to start fish
if test -f /opt/homebrew/bin/brew; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif test -f /home/linuxbrew/.linuxbrew/bin/brew; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

