#!/usr/bin/env zsh

# Exit if not interactive
case $- in
*i*) ;;
*) return ;;
esac

# Include user bins
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
  PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

alias c='clear'
alias q='exit'

# Setup homebrew if installed
for brew_prefix in /opt/homebrew /home/linuxbrew/.linuxbrew ~/.linuxbrew; do
  if [ -x "$brew_prefix/bin/brew" ]; then
    eval "$($brew_prefix/bin/brew shellenv zsh)"
    export HOMEBREW_BUNDLE_FILE=~/.config/Brewfile
    break
  fi
done

# History settings
HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=2000
setopt APPEND_HISTORY
setopt HIST_IGNORE_SPACE
setopt HIST_IGNORE_DUPS

# Load completion
autoload -Uz compinit
compinit

# External command specific configs
if command -v nvim >/dev/null 2>&1; then
  export EDITOR=nvim
  export MANPAGER="nvim +Man!"

  alias sshconf='nvim ~/.ssh/config'
fi

if command -v fzf >/dev/null 2>&1; then
  export FZF_DEFAULT_OPTS_FILE=~/.config/fzfrc
  eval "$(fzf --zsh)"
fi

if command -v starship >/dev/null 2>&1; then
  eval "$(starship init zsh)"
fi

if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init zsh)"
fi

if command -v mise >/dev/null 2>&1; then
  eval "$(mise activate zsh)"
fi

if command -v carapace >/dev/null 2>&1; then
  export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense'
  source <(carapace _carapace)
fi

if command -v eza >/dev/null 2>&1; then
  export EZA_CONFIG_DIR=~/.config/eza
  export EZA_ICONS_AUTO=true

  alias l='eza'
  alias la='eza -al'
  alias ll='eza -l'
  alias tree='eza --tree'
else
  alias ls='ls --color=auto'
  alias l='ls --color=auto'
  alias la='ls -Al --color=auto'
  alias ll='ls -l --color=auto'
fi

if command -v bat >/dev/null 2>&1; then
  export BAT_THEME_DARK="Catppuccin Mocha"
  export BAT_THEME_LIGHT="Catppuccin Latte"

  alias cat='bat -p'
  alias sshpub='bat -p ~/.ssh/id_ed25519.pub'
fi

if command -v rg >/dev/null 2>&1; then
  export RIPGREP_CONFIG_PATH=~/.config/ripgreprc
fi

if command -v brew >/dev/null 2>&1; then
  alias brewfile='chezmoi edit -a --watch $HOMEBREW_BUNDLE_FILE'
  alias brewup='brew bundle install --cleanup'
fi

# Enable Vi keybinds
bindkey -v

# Load custom functions
if [ -f ~/.bash_functions ]; then
  . ~/.bash_functions
fi
