# base settings
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on
set -s escape-time 0
set -g base-index 1
set -g pane-base-index 1
set -gw pane-base-index 1
set -g renumber-windows on
set -g history-limit 100000

# change prefix to ctrl-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# vim style navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# vim like copy and paste
set -gw mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

# splits similar to vim
unbind %
bind v split-window -hc "#{pane_current_path}"
unbind '"'
bind s split-window -vc "#{pane_current_path}"

# new window spawn on the same path
unbind c
bind c new-window -c "#{pane_current_path}"

# reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf\; display "config reloaded"

# Run sessionizer inside a popup so fzf has a TTY
bind f display-popup -E -w 60% -h 12 "bash ~/.config/tmux/sessionizer.sh"
# bind s display-popup -E -w 60% -h 12 "bash ~/.config/tmux/fzf-sessions.sh"

# catppuccin and appearance
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_current_number_color "#{@thm_peach}"
set -g @catppuccin_window_number_position "left"

# Menu style
set -g @catppuccin_menu_selected_style "fg=#{@thm_fg},bold,bg=#{@thm_overlay_0}"

# Status line options
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_status_style "none"
set -g @catppuccin_status_left_separator ""
set -g @catppuccin_status_right_separator "#[fg=#{@thm_surface_0}]"
set -g @catppuccin_status_connect_separator "no" # yes, no
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_module_bg_color "#{@thm_surface_0}"

set -g status-position top
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right ""
set -g status-right "#{?client_prefix,#{#[bg=#{@thm_bg},fg=#{@thm_peach},bold]  #S },#{#[bg=#{@thm_bg},fg=#{@thm_subtext_0}]  #S }}"

set -g window-status-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-style "bg=#{@thm_bg},fg=#{@thm_subtext_0}"
set -g window-status-activity-style "bg=#{@thm_bg},fg=#{@thm_red}"
set -g window-status-bell-style "bg=#{@thm_bg},fg=#{@thm_red},bold"
set -gF window-status-separator "#[bg=#{@thm_bg},fg=#{@thm_overlay_0}]│"

set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-current-style "bg=#{@thm_bg},fg=#{@thm_peach},bold"

# pane border look and feel
set -gw pane-border-format ""
set -gw pane-active-border-style "bg=#{@thm_bg},fg=#{@thm_overlay_0}"
set -gw pane-border-style "bg=#{@thm_bg},fg=#{@thm_surface_0}"
set -gw pane-border-lines single

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
