tap "sst/tap"
# Automate deployment, configuration, and upgrading
brew "ansible"
# Language Server for Ansible Files
brew "ansible-language-server"
# Checks ansible playbooks for practices and behaviour
brew "ansible-lint"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Secure and free password manager for all of your devices
brew "bitwarden-cli"
# Simple wrapper script for the Borg backup software
brew "borgmatic"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Multi-shell multi-command argument completer
brew "carapace"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Isolated development environments using Docker
brew "docker-compose"
# Language service for Docker Compose documents
brew "docker-compose-langserver"
# Platform keystore credential helper for Docker
brew "docker-credential-helper"
# Convert text between DOS, UNIX, and Mac formats
brew "dos2unix"
# More intuitive version of du in rust
brew "dust"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Command-line fuzzy finder written in Go
brew "fzf"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Simple terminal UI for git commands
brew "lazygit"
# Linux virtual machines
brew "lima"
# Language Server for the Lua language
brew "lua-language-server"
# Mac App Store command-line interface
brew "mas"
# Tool for working with usage-spec CLIs
brew "usage"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# NCurses Disk Usage
brew "ncdu"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Port scanning utility for large networks
brew "nmap"
# 7-Zip (high compression file archiver) implementation
brew "p7zip"
# Tool for managing OCI containers and pods
brew "podman"
# Alternative to docker-compose using podman
brew "podman-compose"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Prettier daemon
brew "prettierd"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Utility that provides fast incremental file transfer
brew "rsync"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Autoformat shell script source code
brew "shfmt"
# Cross-shell prompt for astronauts
brew "starship"
# Opinionated Lua code formatter
brew "stylua"
# Very fast implementation of tldr in Rust
brew "tealdeer"
# Terminal multiplexer
brew "tmux"
# Parser generator tool
brew "tree-sitter-cli"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Command-line client for WebSockets
brew "websocat"
# Friendly and fast tool for sending HTTP requests
brew "xh"
# Blazing fast terminal file manager written in Rust, based on async I/O
brew "yazi"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Application uninstaller
cask "appcleaner"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# Display management tool
cask "betterdisplay"
# Voice and text chat software
cask "discord"
cask "font-jetbrains-mono-nerd-font"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Web browser
cask "google-chrome"
# Client for the Google Drive storage service
cask "google-drive"
# Free and open-source media player
cask "iina"
# Desktop sync client for Nextcloud software products
cask "nextcloud"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# G-code generator for 3D printers
cask "orcaslicer"
# Client for Proton Mail and Proton Calendar
cask "proton-mail"
# VPN client focusing on security
cask "protonvpn"
# Control your tools with a few keystrokes
cask "raycast"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Instant messaging application focusing on security
cask "signal"
# Mesh VPN based on WireGuard
cask "tailscale-app"
# Music streaming service with high fidelity sound and hi-def video quality
cask "tidal"
# To-do list
cask "todoist-app"
# Tool to invert scroll direction for physical scroll wheels
cask "unnaturalscrollwheels"
# Multiplayer code editor
cask "zed"
# Gecko based web browser
cask "zen"
mas "Amperfy", id: 1530145038
mas "Bitwarden", id: 1352778147
mas "TestFlight", id: 899247664
mas "WhatsApp", id: 310633997
mas "WireGuard", id: 1451685025
