tap "sst/tap"
# Simple, modern, secure file encryption
brew "age"
# Automate deployment, configuration, and upgrading
brew "ansible"
# Language Server for Ansible Files
brew "ansible-language-server"
# Checks ansible playbooks for practices and behaviour
brew "ansible-lint"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Secure and free password manager for all of your devices
brew "bitwarden-cli"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Multi-shell multi-command argument completer
brew "carapace"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Isolated development environments using Docker
brew "docker-compose"
# Platform keystore credential helper for Docker
brew "docker-credential-helper"
# Convert text between DOS, UNIX, and Mac formats
brew "dos2unix"
# More intuitive version of du in rust
brew "dust"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Lazier way to manage everything docker
brew "lazydocker"
# Simple terminal UI for git commands
brew "lazygit"
# Linux virtual machines
brew "lima"
# Language Server for the Lua language
brew "lua-language-server"
# Mac App Store command-line interface
brew "mas"
# Tool for working with usage-spec CLIs
brew "usage"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Port scanning utility for large networks
brew "nmap"
# 7-Zip (high compression file archiver) implementation
brew "p7zip"
# Tool for managing OCI containers and pods
brew "podman"
# Alternative to docker-compose using podman
brew "podman-compose"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Modern API client that lives in your terminal
brew "posting"
# Framework for managing multi-language pre-commit hooks
brew "pre-commit"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Utility that provides fast incremental file transfer
brew "rsync"
# Rust toolchain installer
brew "rustup"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Autoformat shell script source code
brew "shfmt"
# Editor of encrypted files
brew "sops"
# Command-line utility for SQLx, the Rust SQL toolkit
brew "sqlx-cli"
# Cross-shell prompt for astronauts
brew "starship"
# Opinionated Lua code formatter
brew "stylua"
# Very fast implementation of tldr in Rust
brew "tealdeer"
# Terminal multiplexer
brew "tmux"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Sends magic packets to wake up network-devices
brew "wakeonlan"
# Command-line client for WebSockets
brew "websocat"
# Friendly and fast tool for sending HTTP requests
brew "xh"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# Display management tool
cask "betterdisplay"
# Web browser focusing on privacy
cask "brave-browser"
# Voice and text chat software
cask "discord"
# Desktop client for Ente Auth
cask "ente-auth"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Web browser
cask "google-chrome"
# Client for the Google Drive storage service
cask "google-drive"
# Jellyfin desktop client
cask "jellyfin-media-player"
# JetBrains tools manager
cask "jetbrains-toolbox"
# Desktop sync client for Nextcloud software products
cask "nextcloud"
# Programmable solid 3D CAD modeller
cask "openscad@snapshot"
# G-code generator for 3D printers
cask "orcaslicer"
# VPN client focusing on security
cask "protonvpn"
# Toolbox companion for QMK Firmware
cask "qmk-toolbox"
# Imaging utility to install operating systems to a microSD card
cask "raspberry-pi-imager"
# Control your tools with a few keystrokes
cask "raycast"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Instant messaging application focusing on security
cask "signal"
# Video game digital distribution service
cask "steam"
# Media player based on MPlayer and mplayer2
cask "stolendata-mpv"
# Real time file synchronisation software
cask "syncthing-app"
# Mesh VPN based on WireGuard
cask "tailscale-app"
# Unpacks archive files
cask "the-unarchiver"
# Music streaming service with high fidelity sound and hi-def video quality
cask "tidal"
# To-do list
cask "todoist-app"
# Open-source BitTorrent client
cask "transmission"
# Tool to invert scroll direction for physical scroll wheels
cask "unnaturalscrollwheels"
# Native desktop client for WhatsApp
cask "whatsapp"
# Multiplayer code editor
cask "zed"
mas "Bitwarden", id: 1352778147
mas "keymapp", id: 6472865291
mas "TestFlight", id: 899247664
mas "WireGuard", id: 1451685025
go "cmd/go"
go "cmd/gofmt"
