"$schema" = "https://starship.rs/config-schema.json"
right_format = "$custom"

[custom.bitwarden]
description = "show status of bitwarden-cli"
command = "echo bw"
when = ''' test -n "$BW_SESSION" '''
symbol = " "
style = "blue"
