"$schema" = "https://starship.rs/config-schema.json"
right_format = "$custom"

[custom.chezmoi]
description = "show status of dotfile sync with chezmoi"
command = "echo dotfiles"
when = ''' command -q chezmoi && test -n "$(chezmoi status)"'''
symbol = "!"
style = "dimmed red"

[custom.bitwarden]
description = "show status of bitwarden-cli"
command = "echo bw"
when = ''' test -n "$BW_SESSION" '''
symbol = " "
style = "blue"
